name: Deploy to Render

on:
  push:
    branches: [ main ]
    paths: [ 'server/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          echo "Render will automatically deploy when changes are pushed to main branch"
          echo "No additional action needed - this workflow is for documentation"